# constants.py
import os

# 文本文件列表
TXT_FILES = [
    "/mnt/file2/changye/dataset/Align-Anything-interp/AA_text_image_to_text/cosi_feature_list.txt",
    # "/mnt/file2/changye/dataset/Align-Anything-interp/Align-Anything-Cosi-q0_25/cosi_feature_list.txt",
    # "/mnt/file2/changye/dataset/Align-Anything-interp/Align-Anything-Coccur-q0_25/cosi_feature_list.txt",
    # "/mnt/file2/changye/dataset/Align-Anything-interp/Align-Anything-L0-q0_25/cosi_feature_list.txt",
    "/mnt/file2/changye/dataset/Align-Anything-preference_interp/AA_preference_cosi_0_25/cosi_feature_list.txt",
    "/mnt/file2/changye/dataset/Align-Anything-preference_interp/AA_preference_cosi_0_50/cosi_feature_list.txt",
    "/mnt/file2/changye/dataset/Align-Anything-preference_interp/AA_preference_cosi_0_75/cosi_feature_list.txt",
    # "/mnt/file2/changye/dataset/Align-Anything-preference_interp/AA_preference_cosi_weight/cosi_feature_list.txt",
    "/mnt/file2/changye/dataset/Align-Anything-preference_interp/AA_preference_l0_0_50/cosi_feature_list.txt",
    "/mnt/file2/changye/dataset/Align-Anything-preference_interp/AA_preference_l0_0_75/cosi_feature_list.txt",
    # "/mnt/file2/changye/dataset/RLAIF-V_interp/RLAIF-V_Coccur-q0_25_preference/cosi_feature_list.txt",
    "/mnt/file2/changye/dataset/RLAIF-V_interp/RLAIF-V_Coocur-q0_25/cosi_feature_list.txt",
    "/mnt/file2/changye/dataset/RLAIF-V_interp/RLAIF-V_Coocur-q0_50/cosi_feature_list.txt",
    "/mnt/file2/changye/dataset/RLAIF-V_interp/RLAIF-V_Coocur-q0_75/cosi_feature_list.txt",
    # "/mnt/file2/changye/dataset/RLAIF-V_interp/RLAIF-V_cosi_weight/cosi_feature_list.txt",
    "/mnt/file2/changye/dataset/RLAIF-V_interp/RLAIF-V_Cosi-q0_25/cosi_feature_list.txt",
    "/mnt/file2/changye/dataset/RLAIF-V_interp/RLAIF-V_Cosi-q0_50/cosi_feature_list.txt",
    "/mnt/file2/changye/dataset/RLAIF-V_interp/RLAIF-V_Cosi-q0_75/cosi_feature_list.txt",
    "/mnt/file2/changye/dataset/RLAIF-V_interp/RLAIF-V_L0-q0_50/cosi_feature_list.txt",
    "/mnt/file2/changye/dataset/RLAIF-V_interp/RLAIF-V_L0-q0_75/cosi_feature_list.txt",
    # "/mnt/file2/changye/dataset/RLAIF-V_interp/RLAIF-V-Cosi-q0_25_preference/cosi_feature_list.txt",
    # "/mnt/file2/changye/dataset/RLAIF-V_interp/RLAIF-V-L0-q0_25_preference/cosi_feature_list.txt",
    "/mnt/file2/changye/dataset/Align-Anything-preference_interp/AA_preference_cocour_new_step10_0_10/cosi_feature_list.txt",
    "/mnt/file2/changye/dataset/Align-Anything-preference_interp/AA_preference_cocour_new_step10_0_20/cosi_feature_list.txt",
    "/mnt/file2/changye/dataset/Align-Anything-preference_interp/AA_preference_cocour_new_step10_0_30/cosi_feature_list.txt",
    "/mnt/file2/changye/dataset/Align-Anything-preference_interp/AA_preference_cocour_new_step10_0_40/cosi_feature_list.txt",
    "/mnt/file2/changye/dataset/Align-Anything-preference_interp/AA_preference_cocour_new_step10_0_50/cosi_feature_list.txt",
    "/mnt/file2/changye/dataset/Align-Anything-preference_interp/AA_preference_cocour_new_step10_0_60/cosi_feature_list.txt",
    "/mnt/file2/changye/dataset/Align-Anything-preference_interp/AA_preference_cocour_new_step10_0_70/cosi_feature_list.txt",
    "/mnt/file2/changye/dataset/Align-Anything-preference_interp/AA_preference_cocour_new_step10_0_80/cosi_feature_list.txt",
    "/mnt/file2/changye/dataset/Align-Anything-preference_interp/AA_preference_cocour_new_step10_0_90/cosi_feature_list.txt",
    "/mnt/file2/changye/dataset/Align-Anything-preference_interp/AA_preference_cocour_new_step10_0_100/cosi_feature_list.txt",
    "/mnt/file2/changye/dataset/Align-Anything-preference_interp/AA_preference_cosi_new_step10_0_10/cosi_feature_list.txt",
    "/mnt/file2/changye/dataset/Align-Anything-preference_interp/AA_preference_cosi_new_step10_0_20/cosi_feature_list.txt",
    "/mnt/file2/changye/dataset/Align-Anything-preference_interp/AA_preference_cosi_new_step10_0_30/cosi_feature_list.txt",
    "/mnt/file2/changye/dataset/Align-Anything-preference_interp/AA_preference_cosi_new_step10_0_40/cosi_feature_list.txt",
    "/mnt/file2/changye/dataset/Align-Anything-preference_interp/AA_preference_cosi_new_step10_0_50/cosi_feature_list.txt",
    "/mnt/file2/changye/dataset/Align-Anything-preference_interp/AA_preference_cosi_new_step10_0_60/cosi_feature_list.txt",
    "/mnt/file2/changye/dataset/Align-Anything-preference_interp/AA_preference_cosi_new_step10_0_70/cosi_feature_list.txt",
    "/mnt/file2/changye/dataset/Align-Anything-preference_interp/AA_preference_cosi_new_step10_0_80/cosi_feature_list.txt",
    "/mnt/file2/changye/dataset/Align-Anything-preference_interp/AA_preference_random_0_10/cosi_feature_list.txt",
    "/mnt/file2/changye/dataset/Align-Anything-preference_interp/AA_preference_random_0_20/cosi_feature_list.txt",
    "/mnt/file2/changye/dataset/Align-Anything-preference_interp/AA_preference_random_0_30/cosi_feature_list.txt",
    "/mnt/file2/changye/dataset/Align-Anything-preference_interp/AA_preference_random_0_40/cosi_feature_list.txt",
    "/mnt/file2/changye/dataset/Align-Anything-preference_interp/AA_preference_random_0_50/cosi_feature_list.txt",
    "/mnt/file2/changye/dataset/Align-Anything-preference_interp/AA_preference_random_0_60/cosi_feature_list.txt",
    "/mnt/file2/changye/dataset/Align-Anything-preference_interp/AA_preference_random_0_70/cosi_feature_list.txt",
    "/mnt/file2/changye/dataset/Align-Anything-preference_interp/AA_preference_random_0_80/cosi_feature_list.txt",
    "/mnt/file2/changye/dataset/Align-Anything-preference_interp/AA_preference_random_0_90/cosi_feature_list.txt",
    "/mnt/file2/changye/dataset/Align-Anything-preference_interp/AA_preference_l0_new_step10_0_10/cosi_feature_list.txt",
    "/mnt/file2/changye/dataset/Align-Anything-preference_interp/AA_preference_l0_new_step10_0_20/cosi_feature_list.txt",
    "/mnt/file2/changye/dataset/Align-Anything-preference_interp/AA_preference_l0_new_step10_0_30/cosi_feature_list.txt",
    "/mnt/file2/changye/dataset/Align-Anything-preference_interp/AA_preference_l0_new_step10_0_40/cosi_feature_list.txt",
    "/mnt/file2/changye/dataset/Align-Anything-preference_interp/AA_preference_l0_new_step10_0_50/cosi_feature_list.txt",
    "/mnt/file2/changye/dataset/Align-Anything-preference_interp/AA_preference_l0_new_step10_0_60/cosi_feature_list.txt",
    "/mnt/file2/changye/dataset/Align-Anything-preference_interp/AA_preference_l0_new_step10_0_70/cosi_feature_list.txt",
    "/mnt/file2/changye/dataset/Align-Anything-preference_interp/AA_preference_l0_new_step10_0_80/cosi_feature_list.txt",
]

Chameleon_dir="/mnt/file2/changye/dataset/interp/Align-Anything-preference_chameleon_interp"
Chameleon_FILES = []

for dir in os.listdir(Chameleon_dir):
    if os.path.isdir(os.path.join(Chameleon_dir, dir)):
        Chameleon_FILES.append(os.path.join(Chameleon_dir, dir, "cosi_feature_list.txt"))

# 文件夹名对应分数

SCORE_MAP = {
    "AA_text_image_to_text":106.60,
    # "Align-Anything-L0-q0_25": 73.60,
    # "Align-Anything-Coccur-q0_25": 73.40,
    # "Align-Anything-Cosi-q0_25": 73.87,
    "AA_preference_cosi_0_25": 99.47,
    "AA_preference_cosi_0_50": 94.77,
    "AA_preference_cosi_0_75": None,
    # "AA_preference_cosi_weight": 94.07,
    "AA_preference_l0_0_50": 96.30,
    "AA_preference_l0_0_75": None,
    "RLAIF-V_Coccur-q0_25_preference": 89.20,
    "RLAIF-V_Coocur-q0_25": 82.63,
    "RLAIF-V_Coocur-q0_50": 77.83,
    "RLAIF-V_Coocur-q0_75": 72.93,
    "RLAIF-V_Cosi-q0_25": 78.20,
    "RLAIF-V_Cosi-q0_50": 73.33,
    "RLAIF-V_Cosi-q0_75": 72.77,
    "RLAIF-V_L0-q0_50": 78.00,
    "RLAIF-V_L0-q0_75": 70.83,
    "RLAIF-V-Cosi-q0_25_preference": 93.20,
    "RLAIF-V-L0-q0_25_preference": 90.20,
    "AA_preference_cocour_new_step10_0_100":84.63,
    "AA_preference_cocour_new_step10_0_90":97.50,
    "AA_preference_cocour_new_step10_0_80":98.63,
    "AA_preference_cocour_new_step10_0_70":94.70,
    "AA_preference_cocour_new_step10_0_60":97.10,
    "AA_preference_cocour_new_step10_0_50":108.17,
    "AA_preference_cocour_new_step10_0_40":101.33,
    "AA_preference_cocour_new_step10_0_30":104.37,
    "AA_preference_cocour_new_step10_0_20":99.43,
    "AA_preference_cocour_new_step10_0_10":104.40,
    "AA_preference_cosi_new_step10_0_90":97.87,
    "AA_preference_cosi_new_step10_0_80":101.00,
    "AA_preference_cosi_new_step10_0_70":99.90,
    "AA_preference_cosi_new_step10_0_60":100.27,
    "AA_preference_cosi_new_step10_0_50":101.57,
    "AA_preference_cosi_new_step10_0_40":103.73,
    "AA_preference_cosi_new_step10_0_30":101.87,
    "AA_preference_cosi_new_step10_0_20":104.20,
    "AA_preference_cosi_new_step10_0_10":101.73,
    "AA_preference_l0_new_step10_0_90":None,
    "AA_preference_l0_new_step10_0_80":None,
    "AA_preference_l0_new_step10_0_70":97.93,
    "AA_preference_l0_new_step10_0_60":102.87,
    "AA_preference_l0_new_step10_0_50":104.37,
    "AA_preference_l0_new_step10_0_40":105.87,
    "AA_preference_l0_new_step10_0_30":98.43,
    "AA_preference_l0_new_step10_0_20":104.20,
    "AA_preference_l0_new_step10_0_10":105.10,
    "AA_preference_random_0_90":97.43,
    "AA_preference_random_0_80":102.00,
    "AA_preference_random_0_70":98.67,
    "AA_preference_random_0_60":95.57,
    "AA_preference_random_0_50":98.47,
    "AA_preference_random_0_40":98.27,
    "AA_preference_random_0_30":107.80,
    "AA_preference_random_0_20":98.03,
    "AA_preference_random_0_10":99.87,
}

# 找到除 None 之外的最小和最大分数，用于颜色映射
VALID_SCORES = [s for s in SCORE_MAP.values() if s is not None]
LOWEST_SCORE = min(VALID_SCORES)  # 最低分
HIGHEST_SCORE = max(VALID_SCORES)  # 最高分
